### PR TITLE
create gitlab Matcher

### PR DESCRIPTION
**Pull request by tarfu**
- forked github.go and github_test.go
- made some changes to run with gitlab (gitlab.org) and gitlab instances
- changes are mostly replacing github to gitlab to avoid confusion and add a host parameter because gitlab is often used on private instances
- for everything we do gitlab is url compatible with github

### CODE REVIEW

**Comment by slimsag** [comment]
I'll be able to review this probably today or tomorrow.

If gitlab is very compatible with GitHub, could the code not use almost the same back-end code? Is it really needed to fork `github.go` and `github_test.go` ?

**Comment by tarfu** [comment]
this was the lazy approach ...
you could also just change the hard coded host in github.go and it should
work.
would be much nicer I think ... just a second initializer for a non default
host and you would support github ee as well.

2015-01-23 0:59 GMT+01:00 Stephen Gutekanst <notifications@github.com>:

**Comment by slimsag** [comment]
That sounds like a much nicer approach.

**Comment by tarfu** [comment]
this works for me... anyone else?

**Comment by slimsag** [comment]
That looks much more correct, great work!

It looks like GitLab supports running on your own (non-`gitlab.com`) domain, am I correct in thinking this?

**Comment by tarfu** [comment]
Yes you are. It is the more common usecase of it ...
Am 26.01.2015 05:44 schrieb "Stephen Gutekanst" <notifications@github.com>:

**Comment by slimsag** [comment]
Okay, just wanted to check with someone who knows for certain. I'm going to go ahead and merge this in, but until 2.1 is released it won't appear at `azul3d.org/semver.v2`.

Do you have preference as to when 2.1 is released?

**Pull request merged**
