### PR TITLE
Match import paths with dashes

### PR DESCRIPTION
**Pull request by cgt**
Fix rePkgVersion to match import paths with dashes in them, like
"go-thepkg".

### CODE REVIEW

**Comment by slimsag** [comment]
Thank you! I wasn't aware of this issue.

Could you also add a test for this functionality to `github_test.go` ?

**Comment by cgt** [comment]
Added a few tests. Are they satisfactory?

**Comment by slimsag** [comment]
That is perfect. I truly appreciate it.

- Do you intend to use this on a `go-thepkg` repository? If so, I'll release v1.0.2 today. Otherwise, I'll wait until `v2`.
- Please also see: http://azul3d.org/doc/contributing.html#attribution

Cheers :smile:

**Comment by cgt** [comment]
I currently have a vanity import path built with hand-written HTML files set up for my [go-mwclient](https://github.com/cgt/go-mwclient) package. I intended to make a static page generator for this purpose, but then I discovered this wonderful package and decided to use it instead. I have not yet deployed it, but I have already built the program with the version from my forked repository, so it doesn't make any difference to me if you release it now or later.

If you feel that my contribution to this package is significant enough to warrant mention on the authors page, then I will not object to being added.

**Comment by slimsag** [comment]
> I currently have a vanity import path built with hand-written HTML files set up for my go-mwclient package. I intended to make a static page generator for this purpose, but then I discovered this wonderful package and decided to use it instead. I have not yet deployed it, but I have already built the program with the version from my forked repository, so it doesn't make any difference to me if you release it now or later.

Sounds cool! I am going to try and have `v2` out by the end of today if possible.

> If you feel that my contribution to this package is significant enough to warrant mention on the authors page, then I will not object to being added.

Absolutely, any contribution big or small deserves proper attribution. I'll commit a change for this and /cc you shortly.

**Comment by slimsag** [comment]
> Sounds cool! I am going to try and have v2 out by the end of today if possible.

See http://azul3d.org/news/2015/semver-version-2.html

**Pull request merged**
